### ISSUE TITLE
Recordings aren't being deleted from the pi

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/sidekick#22]
CPTV files appear to stay on the pi even when they have been successfully downloaded. The managementd logs show no delete requests.

**Comment by CameronRP** [comment]
Did you upload the files to the API then see if the files were deleted when it connects to the device next?

**Comment by mjs** [comment]
I didn't do that. Is that how it works? If so, that seems flaky to me - more moving parts and it requires that exactly the same instance of the Sidekick app be brought back to the camera in order for recordings to be deleted. There are many scenarios in which recordings will be left behind and never removed.

I really think each CPTV should be removed from the pi once it has been successfully retrieved from the pi. That's simple and relatively fool proof.

**Comment by CameronRP** [comment]
The reason this was done was if somebody downloaded some recordings but didn't upload them for some reason we don't want to loose those recordings.
I don't think there should be a case where recordings never get deleted. Unless every phone that downloads from a device never returns to that device again.

**Comment by mjs** [comment]
Following on from our phone call, I'm ok with this now.
