### ISSUE TITLE
Login screen: colours make cursor invisible

### ISSUE THREAD

**Issue by mjs** [TheCacophonyProject/sidekick#24]
The fields on the login screen are currently very hard to use because the cursor and field highlight card and nearly invisible. The colour used is very similar to the background colour.

**Comment by CameronRP** [comment]
Can you add a screenshot please.

**Comment by mjs** [comment]
![screenshot_20181217-115049](https://user-images.githubusercontent.com/14993/50059982-aeed2000-01f2-11e9-9af0-f23f2a2803f1.png)

In this shot, the username field is active. The underline disappears and the cursor is (almost) invisible.
